### ISSUE TITLE
USB path is not valid?

### ISSUE THREAD

**Issue by curlyel** [cminyard/ser2net#61]
I'm about to test the mdns discovery feature with ser2net to announce my serial devices for the use with rfc2217.
That's my ser2net config file (device names are symlinked via udev rules):

```
%YAML 1.1
---
define: &banner \r\nser2net port \p device \d [\B] (Debian GNU/Linux)\r\n\r\n

connection: &Zigbee
  accepter: telnet(rfc2217),tcp,2222
  connector: serialdev,
    /dev/zigbee,
    57600n81,local
  options:
    mdns: true
    mdns-sysattrs: true
    mdns-name: Zigbee

connection: &BlueGiga
  accepter: telnet(rfc2217),tcp,2223
  connector: serialdev,
        /dev/bluegiga,
        115200n81,local
  options:
    mdns: true
    mdns-sysattrs: true
    mdns-name: Bluegiga

```
When starting the ser2net service it complains about an invalid usb path for the second device, the BlueGiga serial bluetooth adaptor:
```
SerialPi-1:/etc# systemctl status ser2net
● ser2net.service - Serial port to network proxy
     Loaded: loaded (/lib/systemd/system/ser2net.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-12-15 09:23:58 GMT; 7min ago
       Docs: man:ser2net(8)
   Main PID: 806 (ser2net)
      Tasks: 1 (limit: 2059)
        CPU: 46ms
     CGroup: /system.slice/ser2net.service
             └─806 /usr/sbin/ser2net -n -c /etc/ser2net.yaml -P /run/ser2net.pid

Dec 15 09:23:58 SerialPi-1 systemd[1]: Starting Serial port to network proxy...
Dec 15 09:23:58 SerialPi-1 systemd[1]: Started Serial port to network proxy.
**Dec 15 09:23:58 SerialPi-1 ser2net[806]: Device BlueGiga: usb path is not valid: /sys/class/tty/../../devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/tty/ttyACM0**
```
But the path is there:
```
SerialPi-1:/etc# ls /sys/class/tty/../../devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/tty/ttyACM0
dev  device  power  subsystem  uevent
```

When browsing for the serial devices, they show up anyway:

```
=     lo IPv4 Bluegiga                                      _iostream._tcp       local
   hostname = [SerialPi-1.local]
   address = [127.0.0.1]
   port = [2223]
   txt = ["devicetype=serialusb" "gensiostack=telnet(rfc2217),tcp" "provider=ser2net"]
=     lo IPv4 Zigbee                                        _iostream._tcp       local
   hostname = [SerialPi-1.local]
   address = [127.0.0.1]
   port = [2222]
   txt = ["product=BV 2010/10" "manufacturer=Silicon Labs" "serial=xxxxxxxx" "idVendor=10c4" "idProduct=8b34" "interface=BV 2010/10" "bInterfaceNumber=00" "devicetype=serialusb" "gensiostack=telnet(rfc2217),tcp" "provider=ser2net"]

```
So just in the mdns the device description txt the vendor and name etc. is missing.
**Is it just cosmetic?**

lsusb gets the full information:

```
root@SerialPi-1:/etc# lsusb
Bus 001 Device 005: ID 2458:0001 Bluegiga Technologies BLED112 Bluetooth 4.0 Single Mode Dongle
Bus 001 Device 004: ID 10c4:8b34 Silicon Labs BV 2010/10
```
EDIT:
Should mention the environment:
```
RaspberryPi 3B with Raspberry Pi OS Bullseye
Linux SerialPi-1 5.10.63-v7+ #1488 SMP Thu Nov 18 16:14:44 GMT 2021 armv7l GNU/Linux
```

**Comment by cminyard** [comment]
On Wed, Dec 15, 2021 at 01:50:48AM -0800, curlyel wrote:
> I'm about to test the mdns discovery feature with ser2net to announce my serial devices for the use with rfc2217.
> That's my ser2net config file (device names are symlinked via udev rules):
> 
> ```
> %YAML 1.1
> ---
> define: &banner \r\nser2net port \p device \d [\B] (Debian GNU/Linux)\r\n\r\n
> 
> connection: &Zigbee
>   accepter: telnet(rfc2217),tcp,2222
>   connector: serialdev,
>     /dev/zigbee,
>     57600n81,local
>   options:
>     mdns: true
>     mdns-sysattrs: true
>     mdns-name: Zigbee
> 
> connection: &BlueGiga
>   accepter: telnet(rfc2217),tcp,2223
>   connector: serialdev,
>         /dev/bluegiga,
>         115200n81,local
>   options:
>     mdns: true
>     mdns-sysattrs: true
>     mdns-name: Bluegiga
> 
> ```
> When starting the ser2net service it complains about an invalid usb path for the second device, the BlueGiga serial bluetooth adaptor:
> ```
> SerialPi-1:/etc# systemctl status ser2net
> ● ser2net.service - Serial port to network proxy
>      Loaded: loaded (/lib/systemd/system/ser2net.service; enabled; vendor preset: enabled)
>      Active: active (running) since Wed 2021-12-15 09:23:58 GMT; 7min ago
>        Docs: man:ser2net(8)
>    Main PID: 806 (ser2net)
>       Tasks: 1 (limit: 2059)
>         CPU: 46ms
>      CGroup: /system.slice/ser2net.service
>              └─806 /usr/sbin/ser2net -n -c /etc/ser2net.yaml -P /run/ser2net.pid
> 
> Dec 15 09:23:58 SerialPi-1 systemd[1]: Starting Serial port to network proxy...
> Dec 15 09:23:58 SerialPi-1 systemd[1]: Started Serial port to network proxy.
> **Dec 15 09:23:58 SerialPi-1 ser2net[806]: Device BlueGiga: usb path is not valid: /sys/class/tty/../../devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/tty/ttyACM0**

Yeah, it's not complaining about the path not being there, it's
complaining that the path doesn't match what it should match.

Can you do "ls -l /dev/bluegiga" and give me the output, then follow
symlinks until you hit something that's not a symlink?  I'm making an
assumption that appears to not be true.

> ```
> But the path is there:
> ```
> SerialPi-1:/etc# ls /sys/class/tty/../../devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/tty/ttyACM0
> dev  device  power  subsystem  uevent
> ```
> 
> When browsing for the serial devices, they show up anyway:

Yes, this will not kill the operation, but the attributes about the
device will not be there.

-corey

**Comment by curlyel** [comment]
Sure:

```
root@SerialPi-1:/etc# ls -l /dev/bluegiga
lrwxrwxrwx 1 root root 7 Dec 15 10:20 /dev/bluegiga -> ttyACM0
root@SerialPi-1:/etc# ls -la /dev/ttyACM0
crw-rw-rw- 1 root dialout 166, 0 Dec 15 10:20 /dev/ttyACM0
root@SerialPi-1:/etc#
```

**Comment by cminyard** [comment]
On Wed, Dec 15, 2021 at 05:59:41AM -0800, curlyel wrote:
> Sure:
> 
> ```
> ***@***.***:/etc# ls -l /dev/bluegiga
> lrwxrwxrwx 1 root root 7 Dec 15 10:20 /dev/bluegiga -> ttyACM0
> ***@***.***:/etc# ls -la /dev/ttyACM0
> crw-rw-rw- 1 root dialout 166, 0 Dec 15 10:20 /dev/ttyACM0
> ***@***.***:/etc#
> ```


Hmm, no surprise there, and I tried to fake that with a link:
lrwxrwxrwx  1 root     root          12 Dec 15 07:26 bluegiga -> /dev/ttyUSB0
without issue.

There must be something different about /dev/ttyACM0.  I found some
parsing errors pulling the name out of the connector line, already
pushed to git, but that shouldn't affect your settings.

What should here is that the code follows the /dev/bluegiga symlink to
/dev/ttyACM0, then it pulls out the "ttyACM0" part, then looks it up on
/sys/class/tty/ttyACM0, and follows that symlink.  Whatever that symlink
it, it goes back two directory levels from the end, and that must be
"ttyACM0" or you get this error.

I guess I should have asked you to do:

  ls -l /sys/class/tty/ttyACM0

and send me the output.  Or if you know of an easy way to get a
/dev/ttyACM0 port to appear on my Pi...

-corey

**Comment by curlyel** [comment]
Thanks Corey for looking into it 👍 

Happy to provide the output you've asked for:

```
root@SerialPi-1:/home/pi# ls -l /sys/class/tty/ttyACM0
lrwxrwxrwx 1 root root 0 Dec 17 18:32 /sys/class/tty/ttyACM0 -> ../../devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/tty/ttyACM0
root@SerialPi-1:/home/pi#
```

**Comment by cminyard** [comment]
On Fri, Dec 17, 2021 at 10:36:06AM -0800, curlyel wrote:
> Thanks Corey for looking into it 👍 
> 
> Happy to provide the output you've asked for:
> 
> ```
> ***@***.***:/home/pi# ls -l /sys/class/tty/ttyACM0
> lrwxrwxrwx 1 root root 0 Dec 17 18:32 /sys/class/tty/ttyACM0 -> ../../devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/tty/ttyACM0
> ***@***.***:/home/pi#
> ```

Ok, that's strange, ttyUSB devices have ttyUSB0/tty/ttyUSB0 at the end,
but the ttyACM device is just tty/ttyACM0.  I've pushed up a change to
git that will hopefully fix the issue and give you the proper device
attributes.  Can you check that?

-corey

**Comment by curlyel** [comment]
> Can you check that?

Thanks for providing the update. I've made a new ser2net from your master branch.
Unfortunately, the result is still the same:

```
Dec 18 13:20:53 SerialPi-1 systemd[1]: ser2net.service: Main process exited, code=exited, status=1/FAILURE
Dec 18 13:20:53 SerialPi-1 systemd[1]: ser2net.service: Failed with result 'exit-code'.
Dec 18 13:20:57 SerialPi-1 ser2net: Device Bluegiga: usb path is not valid: /sys/class/tty/../../devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/tty/ttyACM0

root@SerialPi-1:/home/pi/ser2net# which ser2net
/usr/local/sbin/ser2net

root@SerialPi-1:/home/pi/ser2net# ls -la /usr/local/sbin/ser2net
-rwxr-xr-x 1 root root 499240 Dec 18 13:19 /usr/local/sbin/ser2net

root@SerialPi-1:/home/pi/ser2net# ser2net -v
ser2net version 4.3.4
```

BTW: While making the gensio, I spotted these warnings which did not break the build.
Just to let you know though:

```
  CC       gensio_wrap.lo
In file included from gensio_wrap.c:2732:
gensio_python.h: In function ‘gensio_swig_init_lang’:
gensio_python.h:22:5: warning: ‘PyEval_InitThreads’ is deprecated [-Wdeprecated-declarations]
   22 |     PyEval_InitThreads();
      |     ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/python3.9/Python.h:145,
                 from gensio_wrap.c:154:
/usr/include/python3.9/ceval.h:130:37: note: declared here
  130 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
      |                                     ^~~~~~~~~~~~~~~~~~
  CCLD     _gensio.la


```

**Comment by cminyard** [comment]
On Sat, Dec 18, 2021 at 05:44:48AM -0800, curlyel wrote:
> > Can you check that?
> 
> Thanks for providing the update. I've made a new ser2net from your master branch.
> Unfortunately, the result is still the same:

Dang, I messed up, I didn't push to the sourceforge git repository, just
the github repository.  I just pushed it up to sourceforge, can you try
it again?

corey

**Comment by curlyel** [comment]
Hi Corey,
no worries. I guess, I've caused some confusion due to a mistake during my tests and posting the results to early ...
Then you've read my initial reply but certainly missed the edited revision ;-)

_Let me explain:_
I've built ser2net _from the github sources_ - not from sourceforge. So I took the sources _containing_ your recent modifications.
But: When did my first tests with it, I missed that I've kept the former ser2net which came with the Linux distro and my service configuration picked this (old) version of it. Therefore I replied that the issue persisted. **This was wrong**.

After noticing my fault, I replaced the _old_ ser2net with the newly built one - and **the issue disappeared**.

Unfortunately, I dicided to _edit_ my wrong post instead of replying again. This caused the confusion presumably :-(
Sorry for that!

_So again:_
With the new version the error is gone and the mdns announcement contains the Bluegiga's device attributes too:

```
=     lo IPv4 Rfxcomm                                       _iostream._tcp       local
   hostname = [SerialPi-1.local]
   address = [127.0.0.1]
   port = [2224]
   txt = ["product=FT232R USB UART" "manufacturer=FTDI" "serial=xxxxxx" "idVendor=0403" "idProduct=6001" "interface=FT232R USB UART" "bInterfaceNumber=00" "devicetype=serialusb" "gensiostack=telnet(rfc2217),tcp" "provider=ser2net"]
=     lo IPv4 Bluegiga                                      _iostream._tcp       local
   hostname = [SerialPi-1.local]
   address = [127.0.0.1]
   port = [2223]
   txt = ["product=Low Energy Dongle" "manufacturer=Bluegiga" "serial=1" "idVendor=2458" "idProduct=0001" "interface=CDC control" "bInterfaceNumber=00" "devicetype=serialusb" "gensiostack=telnet(rfc2217),tcp" "provider=ser2net"]
=     lo IPv4 Zigbee                                        _iostream._tcp       local
   hostname = [SerialPi-1.local]
   address = [127.0.0.1]
   port = [2222]
   txt = ["product=BV 2010/10" "manufacturer=Silicon Labs" "serial=xxxxx" "idVendor=10c4" "idProduct=8b34" "interface=BV 2010/10" "bInterfaceNumber=00" "devicetype=serialusb" "gensiostack=telnet(rfc2217),tcp" "provider=ser2net"]

```
Many thanks for your immediate help and solution!

**Comment by cminyard** [comment]
Good news. I'm not sure how I missed the second post, I guess I don't
get a new mail when a post is updated.  Thanks for working on this.

The warnings you spotted, BTW, are not something I can do much about,
they are coming from the swig-generated code.  Hopefully the swig
maintainers will fix this soon.

-corey

**Comment by curlyel** [comment]
Many thanks to you for solving the issue.
